version: '3.8'

services:
  web:
    build:
      context: ./guestbook
      dockerfile: Dockerfile
    command: gunicorn guestbook.wsgi:application --bind 0.0.0.0:8000 #python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./guestbook/staticfiles:/home/app/web/staticfiles:z
      - ./guestbook/:/usr/src/app/:z
    expose:
      - 8000
    env_file:
      - ./env.dev
    depends_on:
      - db

  db:
    image: mariadb:latest
    volumes:
      - ./mariadb:/var/lib/mysql:z
    environment:
      - MARIADB_DATABASE=guestbook
      - MARIADB_ROOT_PASSWORD=14565
      - MARIADB_USER=user
      - MARIADB_PASSWORD=14565
    expose:
      - 3306

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./guestbook/staticfiles:/home/app/web/staticfiles:z
