# Generated by Django 4.0.1 on 2022-02-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-date',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
