# Generated by Django 4.0.1 on 2022-12-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbookapp', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
